//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contarct
    {
        public int IdContract { get; set; }
        public int IdClients { get; set; }
        public int IdWorker { get; set; }
        public double CreditAmount { get; set; }
        public int InterestOnALoan { get; set; }
        public int DueDate { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
