//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COfficeEntities1 : DbContext
    {
        public COfficeEntities1()
            : base("name=COfficeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contarct> Contarct { get; set; }
        public virtual DbSet<Mouths> Mouths { get; set; }
        public virtual DbSet<NameCountry> NameCountry { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
